# Generated by Django 5.1.1 on 2024-11-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=3)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('metric_amount', models.IntegerField()),
                ('metric_comment', models.TextField(blank=True, null=True)),
                ('metric_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'salaries',
            },
        ),
    ]
